credentials:
  usernames:
    ceo:
      email: hafizghulamyaseenkhan12@gmail.com
      name: Yaseen Khan
      password: abc123
      roles:
        - admin
    teamuser:
      email: team@3knots.com
      name: Team User
      password: pass456
      roles:
        - viewer
cookie:
  name: 3knotsCEO
  key: some_random_signature_key
  expiry_days: 30
preauthorized:
  emails:
    - team@3knots.com
